import { useState, useEffect } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import ReactMarkdown from 'react-markdown'
import { api } from '../api'

function AICard({ result }) {
  return (
    <div className="card border-indigo-500/30 overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-indigo-600/20 to-violet-600/10 border-b border-indigo-500/20 px-6 py-4">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-lg bg-indigo-600 flex items-center justify-center shadow-lg shadow-indigo-600/20">
            <svg className="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
            </svg>
          </div>
          <div>
            <h2 className="text-white font-semibold">AI Routing Recommendation</h2>
            <p className="text-indigo-300 text-xs">Generated by Halo Production Intelligence</p>
          </div>
          <div className="ml-auto">
            <span className="badge-completed">Order Created</span>
          </div>
        </div>
      </div>

      <div className="p-6 space-y-5">
        {/* Order summary */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {[
            ['Client', result.clientName],
            ['Formula', result.formula],
            ['SKU', result.sku],
            ['Quantity', result.quantity?.toLocaleString() + ' units'],
          ].map(([label, value]) => (
            <div key={label} className="bg-slate-800/50 rounded-lg px-3 py-2.5">
              <p className="text-slate-500 text-xs">{label}</p>
              <p className="text-white text-sm font-medium mt-0.5 truncate">{value}</p>
            </div>
          ))}
        </div>

        {/* Assigned co-packer */}
        {result.assignedCoPacker && (
          <div className="flex items-center gap-3 bg-emerald-500/5 border border-emerald-500/20 rounded-lg px-4 py-3">
            <svg className="w-5 h-5 text-emerald-400 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <div>
              <p className="text-slate-400 text-xs">Assigned Co-Packer</p>
              <p className="text-emerald-400 font-semibold">{result.assignedCoPacker}</p>
            </div>
          </div>
        )}

        {/* AI text */}
        {result.aiRecommendation && (
          <div className="bg-slate-800/40 rounded-lg p-4">
            <div className="flex items-center gap-2 mb-3 text-indigo-400">
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
              </svg>
              <span className="text-xs font-semibold uppercase tracking-wide">Full Analysis</span>
            </div>
            <div className="text-slate-300 text-sm leading-relaxed prose prose-invert prose-sm max-w-none
              [&_strong]:text-white [&_strong]:font-semibold
              [&_hr]:border-slate-700 [&_hr]:my-3
              [&_ul]:mt-1 [&_ul]:space-y-1 [&_li]:text-slate-300
              [&_p]:mb-2 [&_p:last-child]:mb-0">
              <ReactMarkdown>{result.aiRecommendation}</ReactMarkdown>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

export default function NewOrder() {
  const navigate = useNavigate()
  const [formulas, setFormulas] = useState([])
  const [form, setForm] = useState({ clientName: '', formula: '', sku: '', quantity: '', notes: '' })
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [result, setResult] = useState(null)

  useEffect(() => {
    api.formulas.list().then(data => setFormulas(Array.isArray(data) ? data : []))
  }, [])

  const selectedFormula = formulas.find(f => f.name === form.formula)

  const set = (field) => (e) => {
    setForm(prev => ({ ...prev, [field]: e.target.value }))
    if (field === 'formula') setForm(prev => ({ ...prev, formula: e.target.value, sku: '' }))
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    setError('')
    setLoading(true)
    try {
      const data = await api.orders.create({ ...form, quantity: Number(form.quantity) })
      setResult(data)
    } catch (err) {
      setError(err.message || 'Failed to submit order')
    } finally {
      setLoading(false)
    }
  }

  const reset = () => {
    setResult(null)
    setForm({ clientName: '', formula: '', sku: '', quantity: '', notes: '' })
    setError('')
  }

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <Link to="/" className="btn-ghost">
          <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
          </svg>
        </Link>
        <div>
          <h1 className="text-2xl font-bold text-white">New Production Order</h1>
          <p className="text-slate-400 text-sm">Submit an order to get an AI-powered co-packer recommendation</p>
        </div>
      </div>

      {!result ? (
        <form onSubmit={handleSubmit} className="card p-6 space-y-5">
          <div className="grid sm:grid-cols-2 gap-5">
            <div>
              <label className="label">Client Name *</label>
              <input className="input" placeholder="e.g. Apex Wellness Brands" value={form.clientName} onChange={set('clientName')} required />
            </div>
            <div>
              <label className="label">Quantity (units) *</label>
              <input type="number" className="input" placeholder="e.g. 50000" min={1} value={form.quantity} onChange={set('quantity')} required />
            </div>
            <div>
              <label className="label">Formula *</label>
              {formulas.length > 0 ? (
                <select className="input" value={form.formula} onChange={e => setForm(prev => ({ ...prev, formula: e.target.value, sku: '' }))} required>
                  <option value="">Select formula...</option>
                  {formulas.map(f => <option key={f._id} value={f.name}>{f.name}</option>)}
                </select>
              ) : (
                <input className="input" placeholder="e.g. HSV1" value={form.formula} onChange={set('formula')} required />
              )}
            </div>
            <div>
              <label className="label">SKU / Flavor *</label>
              {selectedFormula?.skus?.length > 0 ? (
                <select className="input" value={form.sku} onChange={set('sku')} required>
                  <option value="">Select SKU...</option>
                  {selectedFormula.skus.map(s => <option key={s.name} value={s.name}>{s.name}</option>)}
                </select>
              ) : (
                <input className="input" placeholder="e.g. HSV1-OmegaCore-60ct" value={form.sku} onChange={set('sku')} required />
              )}
            </div>
          </div>

          <div>
            <label className="label">Notes / Special Instructions</label>
            <textarea className="input resize-none" rows={3} placeholder="Rush order, packaging requirements, timeline..." value={form.notes} onChange={set('notes')} />
          </div>

          {error && (
            <div className="bg-red-500/10 border border-red-500/20 rounded-lg px-4 py-3 text-red-400 text-sm">{error}</div>
          )}

          <div className="flex items-center justify-between pt-1">
            <Link to="/" className="btn-secondary text-sm">Cancel</Link>
            <button type="submit" disabled={loading} className="btn-primary text-sm">
              {loading ? (
                <>
                  <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                  Analyzing with AI...
                </>
              ) : (
                <>
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
                  </svg>
                  Submit &amp; Get AI Recommendation
                </>
              )}
            </button>
          </div>
        </form>
      ) : (
        <div className="space-y-4">
          <AICard result={result} />
          <div className="flex items-center justify-between">
            <button onClick={reset} className="btn-secondary text-sm">Submit Another Order</button>
            <Link to="/" className="btn-primary text-sm">View Dashboard</Link>
          </div>
        </div>
      )}
    </div>
  )
}
